### ISSUE TITLE
投稿！仿雷达加载组件

### ISSUE THREAD

**Issue by Hellager** [ZiYi0414/handsome-css3-lib#2]
如题，我也是从网上搜来的，具体代码见
[splashscreen.html](https://github.com/Hellager/mission-backup/blob/main/splashscreen.html)

**Comment by ZiYi0414** [comment]
组件必须仅由CSS和HTML就可以实现效果哦。

**Comment by Hellager** [comment]
好吧，是我没看清要求，不好意思不好意思😂

**Comment by ZiYi0414** [comment]
没关系呀 宝贝
